export const SET_INGREDIENTS: 'SET_INGREDIENTS' = 'SET_INGREDIENTS';
export const SET_SORTED_INGREDIENTS: 'SET_SORTED_INGREDIENTS' =
  'SET_SORTED_INGREDIENTS';
export const INCREMENT: 'INCREMENT' = 'INCREMENT';
export const DECREMENT: 'DECREMENT' = 'DECREMENT';
export const CLEAR_COUNTERS: 'CLEAR_COUNTERS' = 'CLEAR_COUNTERS';
export const INGREDIENTS_CONNECTION_START: 'INGREDIENTS_CONNECTION_START' =
  'INGREDIENTS_CONNECTION_START';
export const INGREDIENTS_CONNECTION_SUCCESS: 'INGREDIENTS_CONNECTION_SUCCESS' =
  'INGREDIENTS_CONNECTION_SUCCESS';
export const INGREDIENTS_CONNECTION_FAILED: 'INGREDIENTS_CONNECTION_FAILED' =
  'INGREDIENTS_CONNECTION_FAILED';
