export const SET_INGREDIENTS: 'SET_INGREDIENTS' = 'SET_INGREDIENTS';
export const SET_SORTED_INGREDIENTS: 'SET_SORTED_INGREDIENTS' =
  'SET_SORTED_INGREDIENTS';
export const INCREMENT: 'INCREMENT' = 'INCREMENT';
export const DECREMENT: 'DECREMENT' = 'DECREMENT';
export const CLEAR_COUNTERS: 'CLEAR_COUNTERS' = 'CLEAR_COUNTERS';
