export const LOGIN: 'LOGIN' = 'LOGIN';
export const REGISTER: 'REGISTER' = 'REGISTER';
export const LOGOUT: 'LOGOUT' = 'LOGOUT';
export const GET_USER: 'GET_USER' = 'GET_USER';
export const UPDATE_USER: 'UPDATE_USER' = 'UPDATE_USER';
export const REFRESH_TOKEN: 'REFRESH_TOKEN' = 'REFRESH_TOKEN';
export const RESTORE_PASSWORD: 'RESTORE_PASSWORD' = 'RESTORE_PASSWORD';
export const RESET_PASSWORD: 'RESET_PASSWORD' = 'RESET_PASSWORD';
export const USER_REQUEST_SENT: 'USER_REQUEST_SENT' = 'USER_REQUEST_SENT';
export const USER_REQUEST_SUCCESS: 'USER_REQUEST_SUCCESS' =
  'USER_REQUEST_SUCCESS';
export const USER_REQUEST_FAILED: 'USER_REQUEST_FAILED' = 'USER_REQUEST_FAILED';
export const SET_AUTH: 'SET_AUTH' = 'SET_AUTH';
export const SET_UNAUTH: 'SET_UNAUTH' = 'SET_UNAUTH';
