export const WS_FEED_CONNECTION_START: 'WS_FEED_CONNECTION_START' =
  'WS_FEED_CONNECTION_START';
export const WS_FEED_CONNECTION_SUCCESS: 'WS_FEED_CONNECTION_SUCCESS' =
  'WS_FEED_CONNECTION_SUCCESS';
export const WS_FEED_CONNECTION_ERROR: 'WS_FEED_CONNECTION_ERROR' =
  'WS_FEED_CONNECTION_ERROR';
export const WS_FEED_CONNECTION_CLOSED: 'WS_FEED_CONNECTION_CLOSED' =
  'WS_FEED_CONNECTION_CLOSED';
export const WS_HISTORY_CONNECTION_START: 'WS_HISTORY_CONNECTION_START' =
  'WS_HISTORY_CONNECTION_START';
export const WS_HISTORY_CONNECTION_SUCCESS: 'WS_HISTORY_CONNECTION_SUCCESS' =
  'WS_HISTORY_CONNECTION_SUCCESS';
export const WS_HISTORY_CONNECTION_ERROR: 'WS_HISTORY_CONNECTION_ERROR' =
  'WS_HISTORY_CONNECTION_ERROR';
export const WS_HISTORY_CONNECTION_CLOSED: 'WS_HISTORY_CONNECTION_CLOSED' =
  'WS_HISTORY_CONNECTION_CLOSED';
export const WS_GET_ALL_ORDERS: 'WS_GET_ALL_ORDERS' = 'WS_GET_ALL_ORDERS';
export const WS_GET_HISTORY_ORDERS: 'WS_GET_HISTORY_ORDERS' =
  'WS_GET_HISTORY_ORDERS';
export const WS_SEND_MESSAGE: 'WS_SEND_MESSAGE' = 'WS_SEND_MESSAGE';
